#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CarritoBD")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTbl_Cargo(Tbl_Cargo instance);
    partial void UpdateTbl_Cargo(Tbl_Cargo instance);
    partial void DeleteTbl_Cargo(Tbl_Cargo instance);
    partial void InsertTbl_Categoria(Tbl_Categoria instance);
    partial void UpdateTbl_Categoria(Tbl_Categoria instance);
    partial void DeleteTbl_Categoria(Tbl_Categoria instance);
    partial void InsertTbl_Cliente(Tbl_Cliente instance);
    partial void UpdateTbl_Cliente(Tbl_Cliente instance);
    partial void DeleteTbl_Cliente(Tbl_Cliente instance);
    partial void InsertTbl_DetallePedido(Tbl_DetallePedido instance);
    partial void UpdateTbl_DetallePedido(Tbl_DetallePedido instance);
    partial void DeleteTbl_DetallePedido(Tbl_DetallePedido instance);
    partial void InsertTbl_Empleado(Tbl_Empleado instance);
    partial void UpdateTbl_Empleado(Tbl_Empleado instance);
    partial void DeleteTbl_Empleado(Tbl_Empleado instance);
    partial void InsertTbl_Pedido(Tbl_Pedido instance);
    partial void UpdateTbl_Pedido(Tbl_Pedido instance);
    partial void DeleteTbl_Pedido(Tbl_Pedido instance);
    partial void InsertTbl_Producto(Tbl_Producto instance);
    partial void UpdateTbl_Producto(Tbl_Producto instance);
    partial void DeleteTbl_Producto(Tbl_Producto instance);
    partial void InsertTbl_Usuario(Tbl_Usuario instance);
    partial void UpdateTbl_Usuario(Tbl_Usuario instance);
    partial void DeleteTbl_Usuario(Tbl_Usuario instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::CapaDatos.Properties.Settings.Default.CarritoBDConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tbl_Cargo> Tbl_Cargo
		{
			get
			{
				return this.GetTable<Tbl_Cargo>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Categoria> Tbl_Categoria
		{
			get
			{
				return this.GetTable<Tbl_Categoria>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Cliente> Tbl_Cliente
		{
			get
			{
				return this.GetTable<Tbl_Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_DetallePedido> Tbl_DetallePedido
		{
			get
			{
				return this.GetTable<Tbl_DetallePedido>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Empleado> Tbl_Empleado
		{
			get
			{
				return this.GetTable<Tbl_Empleado>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Pedido> Tbl_Pedido
		{
			get
			{
				return this.GetTable<Tbl_Pedido>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Producto> Tbl_Producto
		{
			get
			{
				return this.GetTable<Tbl_Producto>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Usuario> Tbl_Usuario
		{
			get
			{
				return this.GetTable<Tbl_Usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Cargo")]
	public partial class Tbl_Cargo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_cargo;
		
		private string _Nombre;
		
		private System.Nullable<char> _Estado;
		
		private EntitySet<Tbl_Empleado> _Tbl_Empleado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_cargoChanging(int value);
    partial void OnId_cargoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnEstadoChanging(System.Nullable<char> value);
    partial void OnEstadoChanged();
    #endregion
		
		public Tbl_Cargo()
		{
			this._Tbl_Empleado = new EntitySet<Tbl_Empleado>(new Action<Tbl_Empleado>(this.attach_Tbl_Empleado), new Action<Tbl_Empleado>(this.detach_Tbl_Empleado));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_cargo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_cargo
		{
			get
			{
				return this._Id_cargo;
			}
			set
			{
				if ((this._Id_cargo != value))
				{
					this.OnId_cargoChanging(value);
					this.SendPropertyChanging();
					this._Id_cargo = value;
					this.SendPropertyChanged("Id_cargo");
					this.OnId_cargoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Char(1)")]
		public System.Nullable<char> Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Cargo_Tbl_Empleado", Storage="_Tbl_Empleado", ThisKey="Id_cargo", OtherKey="Id_cargo")]
		public EntitySet<Tbl_Empleado> Tbl_Empleado
		{
			get
			{
				return this._Tbl_Empleado;
			}
			set
			{
				this._Tbl_Empleado.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Empleado(Tbl_Empleado entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Cargo = this;
		}
		
		private void detach_Tbl_Empleado(Tbl_Empleado entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Cargo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Categoria")]
	public partial class Tbl_Categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_categoria;
		
		private string _cat_Nombre;
		
		private System.Nullable<int> _Id_producto;
		
		private string _cat_Descripcion;
		
		private EntitySet<Tbl_DetallePedido> _Tbl_DetallePedido;
		
		private EntityRef<Tbl_Producto> _Tbl_Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_categoriaChanging(int value);
    partial void OnId_categoriaChanged();
    partial void Oncat_NombreChanging(string value);
    partial void Oncat_NombreChanged();
    partial void OnId_productoChanging(System.Nullable<int> value);
    partial void OnId_productoChanged();
    partial void Oncat_DescripcionChanging(string value);
    partial void Oncat_DescripcionChanged();
    #endregion
		
		public Tbl_Categoria()
		{
			this._Tbl_DetallePedido = new EntitySet<Tbl_DetallePedido>(new Action<Tbl_DetallePedido>(this.attach_Tbl_DetallePedido), new Action<Tbl_DetallePedido>(this.detach_Tbl_DetallePedido));
			this._Tbl_Producto = default(EntityRef<Tbl_Producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_categoria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_categoria
		{
			get
			{
				return this._Id_categoria;
			}
			set
			{
				if ((this._Id_categoria != value))
				{
					this.OnId_categoriaChanging(value);
					this.SendPropertyChanging();
					this._Id_categoria = value;
					this.SendPropertyChanged("Id_categoria");
					this.OnId_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_Nombre", DbType="VarChar(100)")]
		public string cat_Nombre
		{
			get
			{
				return this._cat_Nombre;
			}
			set
			{
				if ((this._cat_Nombre != value))
				{
					this.Oncat_NombreChanging(value);
					this.SendPropertyChanging();
					this._cat_Nombre = value;
					this.SendPropertyChanged("cat_Nombre");
					this.Oncat_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_producto", DbType="Int")]
		public System.Nullable<int> Id_producto
		{
			get
			{
				return this._Id_producto;
			}
			set
			{
				if ((this._Id_producto != value))
				{
					if (this._Tbl_Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_productoChanging(value);
					this.SendPropertyChanging();
					this._Id_producto = value;
					this.SendPropertyChanged("Id_producto");
					this.OnId_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_Descripcion", DbType="VarChar(200)")]
		public string cat_Descripcion
		{
			get
			{
				return this._cat_Descripcion;
			}
			set
			{
				if ((this._cat_Descripcion != value))
				{
					this.Oncat_DescripcionChanging(value);
					this.SendPropertyChanging();
					this._cat_Descripcion = value;
					this.SendPropertyChanged("cat_Descripcion");
					this.Oncat_DescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Categoria_Tbl_DetallePedido", Storage="_Tbl_DetallePedido", ThisKey="Id_categoria", OtherKey="Id_categoria")]
		public EntitySet<Tbl_DetallePedido> Tbl_DetallePedido
		{
			get
			{
				return this._Tbl_DetallePedido;
			}
			set
			{
				this._Tbl_DetallePedido.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Producto_Tbl_Categoria", Storage="_Tbl_Producto", ThisKey="Id_producto", OtherKey="Id_producto", IsForeignKey=true)]
		public Tbl_Producto Tbl_Producto
		{
			get
			{
				return this._Tbl_Producto.Entity;
			}
			set
			{
				Tbl_Producto previousValue = this._Tbl_Producto.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Producto.Entity = null;
						previousValue.Tbl_Categoria.Remove(this);
					}
					this._Tbl_Producto.Entity = value;
					if ((value != null))
					{
						value.Tbl_Categoria.Add(this);
						this._Id_producto = value.Id_producto;
					}
					else
					{
						this._Id_producto = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_Producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_DetallePedido(Tbl_DetallePedido entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Categoria = this;
		}
		
		private void detach_Tbl_DetallePedido(Tbl_DetallePedido entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Cliente")]
	public partial class Tbl_Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_cliente;
		
		private string _cli_Nombre;
		
		private string _cli_Apellido;
		
		private string _cli_Telefono;
		
		private string _cli_Direccion;
		
		private string _cli_Correo;
		
		private string _cli_Cedula;
		
		private string _cli_password;
		
		private string _cli_Usuario;
		
		private EntitySet<Tbl_Pedido> _Tbl_Pedido;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_clienteChanging(int value);
    partial void OnId_clienteChanged();
    partial void Oncli_NombreChanging(string value);
    partial void Oncli_NombreChanged();
    partial void Oncli_ApellidoChanging(string value);
    partial void Oncli_ApellidoChanged();
    partial void Oncli_TelefonoChanging(string value);
    partial void Oncli_TelefonoChanged();
    partial void Oncli_DireccionChanging(string value);
    partial void Oncli_DireccionChanged();
    partial void Oncli_CorreoChanging(string value);
    partial void Oncli_CorreoChanged();
    partial void Oncli_CedulaChanging(string value);
    partial void Oncli_CedulaChanged();
    partial void Oncli_passwordChanging(string value);
    partial void Oncli_passwordChanged();
    partial void Oncli_UsuarioChanging(string value);
    partial void Oncli_UsuarioChanged();
    #endregion
		
		public Tbl_Cliente()
		{
			this._Tbl_Pedido = new EntitySet<Tbl_Pedido>(new Action<Tbl_Pedido>(this.attach_Tbl_Pedido), new Action<Tbl_Pedido>(this.detach_Tbl_Pedido));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_cliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_cliente
		{
			get
			{
				return this._Id_cliente;
			}
			set
			{
				if ((this._Id_cliente != value))
				{
					this.OnId_clienteChanging(value);
					this.SendPropertyChanging();
					this._Id_cliente = value;
					this.SendPropertyChanged("Id_cliente");
					this.OnId_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_Nombre", DbType="VarChar(100)")]
		public string cli_Nombre
		{
			get
			{
				return this._cli_Nombre;
			}
			set
			{
				if ((this._cli_Nombre != value))
				{
					this.Oncli_NombreChanging(value);
					this.SendPropertyChanging();
					this._cli_Nombre = value;
					this.SendPropertyChanged("cli_Nombre");
					this.Oncli_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_Apellido", DbType="VarChar(100)")]
		public string cli_Apellido
		{
			get
			{
				return this._cli_Apellido;
			}
			set
			{
				if ((this._cli_Apellido != value))
				{
					this.Oncli_ApellidoChanging(value);
					this.SendPropertyChanging();
					this._cli_Apellido = value;
					this.SendPropertyChanged("cli_Apellido");
					this.Oncli_ApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_Telefono", DbType="VarChar(13)")]
		public string cli_Telefono
		{
			get
			{
				return this._cli_Telefono;
			}
			set
			{
				if ((this._cli_Telefono != value))
				{
					this.Oncli_TelefonoChanging(value);
					this.SendPropertyChanging();
					this._cli_Telefono = value;
					this.SendPropertyChanged("cli_Telefono");
					this.Oncli_TelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_Direccion", DbType="VarChar(100)")]
		public string cli_Direccion
		{
			get
			{
				return this._cli_Direccion;
			}
			set
			{
				if ((this._cli_Direccion != value))
				{
					this.Oncli_DireccionChanging(value);
					this.SendPropertyChanging();
					this._cli_Direccion = value;
					this.SendPropertyChanged("cli_Direccion");
					this.Oncli_DireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_Correo", DbType="VarChar(100)")]
		public string cli_Correo
		{
			get
			{
				return this._cli_Correo;
			}
			set
			{
				if ((this._cli_Correo != value))
				{
					this.Oncli_CorreoChanging(value);
					this.SendPropertyChanging();
					this._cli_Correo = value;
					this.SendPropertyChanged("cli_Correo");
					this.Oncli_CorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_Cedula", DbType="VarChar(13)")]
		public string cli_Cedula
		{
			get
			{
				return this._cli_Cedula;
			}
			set
			{
				if ((this._cli_Cedula != value))
				{
					this.Oncli_CedulaChanging(value);
					this.SendPropertyChanging();
					this._cli_Cedula = value;
					this.SendPropertyChanged("cli_Cedula");
					this.Oncli_CedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_password", DbType="VarChar(100)")]
		public string cli_password
		{
			get
			{
				return this._cli_password;
			}
			set
			{
				if ((this._cli_password != value))
				{
					this.Oncli_passwordChanging(value);
					this.SendPropertyChanging();
					this._cli_password = value;
					this.SendPropertyChanged("cli_password");
					this.Oncli_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_Usuario", DbType="VarChar(100)")]
		public string cli_Usuario
		{
			get
			{
				return this._cli_Usuario;
			}
			set
			{
				if ((this._cli_Usuario != value))
				{
					this.Oncli_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._cli_Usuario = value;
					this.SendPropertyChanged("cli_Usuario");
					this.Oncli_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Cliente_Tbl_Pedido", Storage="_Tbl_Pedido", ThisKey="Id_cliente", OtherKey="Id_cliente")]
		public EntitySet<Tbl_Pedido> Tbl_Pedido
		{
			get
			{
				return this._Tbl_Pedido;
			}
			set
			{
				this._Tbl_Pedido.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Pedido(Tbl_Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Cliente = this;
		}
		
		private void detach_Tbl_Pedido(Tbl_Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_DetallePedido")]
	public partial class Tbl_DetallePedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_detalle;
		
		private System.Nullable<int> _Id_producto;
		
		private System.Nullable<int> _Id_pedido;
		
		private System.Nullable<int> _Id_categoria;
		
		private System.Nullable<int> _Cantidad;
		
		private System.Nullable<double> _Precioventa;
		
		private System.Nullable<double> _Importe;
		
		private EntityRef<Tbl_Categoria> _Tbl_Categoria;
		
		private EntityRef<Tbl_Pedido> _Tbl_Pedido;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_detalleChanging(int value);
    partial void OnId_detalleChanged();
    partial void OnId_productoChanging(System.Nullable<int> value);
    partial void OnId_productoChanged();
    partial void OnId_pedidoChanging(System.Nullable<int> value);
    partial void OnId_pedidoChanged();
    partial void OnId_categoriaChanging(System.Nullable<int> value);
    partial void OnId_categoriaChanged();
    partial void OnCantidadChanging(System.Nullable<int> value);
    partial void OnCantidadChanged();
    partial void OnPrecioventaChanging(System.Nullable<double> value);
    partial void OnPrecioventaChanged();
    partial void OnImporteChanging(System.Nullable<double> value);
    partial void OnImporteChanged();
    #endregion
		
		public Tbl_DetallePedido()
		{
			this._Tbl_Categoria = default(EntityRef<Tbl_Categoria>);
			this._Tbl_Pedido = default(EntityRef<Tbl_Pedido>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_detalle", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_detalle
		{
			get
			{
				return this._Id_detalle;
			}
			set
			{
				if ((this._Id_detalle != value))
				{
					this.OnId_detalleChanging(value);
					this.SendPropertyChanging();
					this._Id_detalle = value;
					this.SendPropertyChanged("Id_detalle");
					this.OnId_detalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_producto", DbType="Int")]
		public System.Nullable<int> Id_producto
		{
			get
			{
				return this._Id_producto;
			}
			set
			{
				if ((this._Id_producto != value))
				{
					this.OnId_productoChanging(value);
					this.SendPropertyChanging();
					this._Id_producto = value;
					this.SendPropertyChanged("Id_producto");
					this.OnId_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_pedido", DbType="Int")]
		public System.Nullable<int> Id_pedido
		{
			get
			{
				return this._Id_pedido;
			}
			set
			{
				if ((this._Id_pedido != value))
				{
					if (this._Tbl_Pedido.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_pedidoChanging(value);
					this.SendPropertyChanging();
					this._Id_pedido = value;
					this.SendPropertyChanged("Id_pedido");
					this.OnId_pedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_categoria", DbType="Int")]
		public System.Nullable<int> Id_categoria
		{
			get
			{
				return this._Id_categoria;
			}
			set
			{
				if ((this._Id_categoria != value))
				{
					if (this._Tbl_Categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_categoriaChanging(value);
					this.SendPropertyChanging();
					this._Id_categoria = value;
					this.SendPropertyChanged("Id_categoria");
					this.OnId_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this.OnCantidadChanging(value);
					this.SendPropertyChanging();
					this._Cantidad = value;
					this.SendPropertyChanged("Cantidad");
					this.OnCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precioventa", DbType="Float")]
		public System.Nullable<double> Precioventa
		{
			get
			{
				return this._Precioventa;
			}
			set
			{
				if ((this._Precioventa != value))
				{
					this.OnPrecioventaChanging(value);
					this.SendPropertyChanging();
					this._Precioventa = value;
					this.SendPropertyChanged("Precioventa");
					this.OnPrecioventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Importe", DbType="Float")]
		public System.Nullable<double> Importe
		{
			get
			{
				return this._Importe;
			}
			set
			{
				if ((this._Importe != value))
				{
					this.OnImporteChanging(value);
					this.SendPropertyChanging();
					this._Importe = value;
					this.SendPropertyChanged("Importe");
					this.OnImporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Categoria_Tbl_DetallePedido", Storage="_Tbl_Categoria", ThisKey="Id_categoria", OtherKey="Id_categoria", IsForeignKey=true)]
		public Tbl_Categoria Tbl_Categoria
		{
			get
			{
				return this._Tbl_Categoria.Entity;
			}
			set
			{
				Tbl_Categoria previousValue = this._Tbl_Categoria.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Categoria.Entity = null;
						previousValue.Tbl_DetallePedido.Remove(this);
					}
					this._Tbl_Categoria.Entity = value;
					if ((value != null))
					{
						value.Tbl_DetallePedido.Add(this);
						this._Id_categoria = value.Id_categoria;
					}
					else
					{
						this._Id_categoria = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_Categoria");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Pedido_Tbl_DetallePedido", Storage="_Tbl_Pedido", ThisKey="Id_pedido", OtherKey="Id_pedido", IsForeignKey=true)]
		public Tbl_Pedido Tbl_Pedido
		{
			get
			{
				return this._Tbl_Pedido.Entity;
			}
			set
			{
				Tbl_Pedido previousValue = this._Tbl_Pedido.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Pedido.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Pedido.Entity = null;
						previousValue.Tbl_DetallePedido.Remove(this);
					}
					this._Tbl_Pedido.Entity = value;
					if ((value != null))
					{
						value.Tbl_DetallePedido.Add(this);
						this._Id_pedido = value.Id_pedido;
					}
					else
					{
						this._Id_pedido = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_Pedido");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Empleado")]
	public partial class Tbl_Empleado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_empleado;
		
		private string _empl_nombre;
		
		private string _empl_apellido;
		
		private System.Nullable<int> _Id_cargo;
		
		private System.Nullable<int> _Id_pedido;
		
		private EntitySet<Tbl_Usuario> _Tbl_Usuario;
		
		private EntityRef<Tbl_Cargo> _Tbl_Cargo;
		
		private EntityRef<Tbl_Pedido> _Tbl_Pedido;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_empleadoChanging(int value);
    partial void OnId_empleadoChanged();
    partial void Onempl_nombreChanging(string value);
    partial void Onempl_nombreChanged();
    partial void Onempl_apellidoChanging(string value);
    partial void Onempl_apellidoChanged();
    partial void OnId_cargoChanging(System.Nullable<int> value);
    partial void OnId_cargoChanged();
    partial void OnId_pedidoChanging(System.Nullable<int> value);
    partial void OnId_pedidoChanged();
    #endregion
		
		public Tbl_Empleado()
		{
			this._Tbl_Usuario = new EntitySet<Tbl_Usuario>(new Action<Tbl_Usuario>(this.attach_Tbl_Usuario), new Action<Tbl_Usuario>(this.detach_Tbl_Usuario));
			this._Tbl_Cargo = default(EntityRef<Tbl_Cargo>);
			this._Tbl_Pedido = default(EntityRef<Tbl_Pedido>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_empleado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_empleado
		{
			get
			{
				return this._Id_empleado;
			}
			set
			{
				if ((this._Id_empleado != value))
				{
					this.OnId_empleadoChanging(value);
					this.SendPropertyChanging();
					this._Id_empleado = value;
					this.SendPropertyChanged("Id_empleado");
					this.OnId_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empl_nombre", DbType="VarChar(100)")]
		public string empl_nombre
		{
			get
			{
				return this._empl_nombre;
			}
			set
			{
				if ((this._empl_nombre != value))
				{
					this.Onempl_nombreChanging(value);
					this.SendPropertyChanging();
					this._empl_nombre = value;
					this.SendPropertyChanged("empl_nombre");
					this.Onempl_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empl_apellido", DbType="VarChar(100)")]
		public string empl_apellido
		{
			get
			{
				return this._empl_apellido;
			}
			set
			{
				if ((this._empl_apellido != value))
				{
					this.Onempl_apellidoChanging(value);
					this.SendPropertyChanging();
					this._empl_apellido = value;
					this.SendPropertyChanged("empl_apellido");
					this.Onempl_apellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_cargo", DbType="Int")]
		public System.Nullable<int> Id_cargo
		{
			get
			{
				return this._Id_cargo;
			}
			set
			{
				if ((this._Id_cargo != value))
				{
					if (this._Tbl_Cargo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_cargoChanging(value);
					this.SendPropertyChanging();
					this._Id_cargo = value;
					this.SendPropertyChanged("Id_cargo");
					this.OnId_cargoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_pedido", DbType="Int")]
		public System.Nullable<int> Id_pedido
		{
			get
			{
				return this._Id_pedido;
			}
			set
			{
				if ((this._Id_pedido != value))
				{
					if (this._Tbl_Pedido.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_pedidoChanging(value);
					this.SendPropertyChanging();
					this._Id_pedido = value;
					this.SendPropertyChanged("Id_pedido");
					this.OnId_pedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Empleado_Tbl_Usuario", Storage="_Tbl_Usuario", ThisKey="Id_empleado", OtherKey="Id_empleado")]
		public EntitySet<Tbl_Usuario> Tbl_Usuario
		{
			get
			{
				return this._Tbl_Usuario;
			}
			set
			{
				this._Tbl_Usuario.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Cargo_Tbl_Empleado", Storage="_Tbl_Cargo", ThisKey="Id_cargo", OtherKey="Id_cargo", IsForeignKey=true)]
		public Tbl_Cargo Tbl_Cargo
		{
			get
			{
				return this._Tbl_Cargo.Entity;
			}
			set
			{
				Tbl_Cargo previousValue = this._Tbl_Cargo.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Cargo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Cargo.Entity = null;
						previousValue.Tbl_Empleado.Remove(this);
					}
					this._Tbl_Cargo.Entity = value;
					if ((value != null))
					{
						value.Tbl_Empleado.Add(this);
						this._Id_cargo = value.Id_cargo;
					}
					else
					{
						this._Id_cargo = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_Cargo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Pedido_Tbl_Empleado", Storage="_Tbl_Pedido", ThisKey="Id_pedido", OtherKey="Id_pedido", IsForeignKey=true)]
		public Tbl_Pedido Tbl_Pedido
		{
			get
			{
				return this._Tbl_Pedido.Entity;
			}
			set
			{
				Tbl_Pedido previousValue = this._Tbl_Pedido.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Pedido.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Pedido.Entity = null;
						previousValue.Tbl_Empleado.Remove(this);
					}
					this._Tbl_Pedido.Entity = value;
					if ((value != null))
					{
						value.Tbl_Empleado.Add(this);
						this._Id_pedido = value.Id_pedido;
					}
					else
					{
						this._Id_pedido = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_Pedido");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Usuario(Tbl_Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Empleado = this;
		}
		
		private void detach_Tbl_Usuario(Tbl_Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Empleado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Pedido")]
	public partial class Tbl_Pedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_pedido;
		
		private System.Nullable<int> _Id_cliente;
		
		private System.Nullable<int> _Id_empleado;
		
		private System.Nullable<System.DateTime> _Fechapedido;
		
		private System.Nullable<double> _subtotal;
		
		private System.Nullable<double> _total;
		
		private EntitySet<Tbl_DetallePedido> _Tbl_DetallePedido;
		
		private EntitySet<Tbl_Empleado> _Tbl_Empleado;
		
		private EntityRef<Tbl_Cliente> _Tbl_Cliente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_pedidoChanging(int value);
    partial void OnId_pedidoChanged();
    partial void OnId_clienteChanging(System.Nullable<int> value);
    partial void OnId_clienteChanged();
    partial void OnId_empleadoChanging(System.Nullable<int> value);
    partial void OnId_empleadoChanged();
    partial void OnFechapedidoChanging(System.Nullable<System.DateTime> value);
    partial void OnFechapedidoChanged();
    partial void OnsubtotalChanging(System.Nullable<double> value);
    partial void OnsubtotalChanged();
    partial void OntotalChanging(System.Nullable<double> value);
    partial void OntotalChanged();
    #endregion
		
		public Tbl_Pedido()
		{
			this._Tbl_DetallePedido = new EntitySet<Tbl_DetallePedido>(new Action<Tbl_DetallePedido>(this.attach_Tbl_DetallePedido), new Action<Tbl_DetallePedido>(this.detach_Tbl_DetallePedido));
			this._Tbl_Empleado = new EntitySet<Tbl_Empleado>(new Action<Tbl_Empleado>(this.attach_Tbl_Empleado), new Action<Tbl_Empleado>(this.detach_Tbl_Empleado));
			this._Tbl_Cliente = default(EntityRef<Tbl_Cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_pedido", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_pedido
		{
			get
			{
				return this._Id_pedido;
			}
			set
			{
				if ((this._Id_pedido != value))
				{
					this.OnId_pedidoChanging(value);
					this.SendPropertyChanging();
					this._Id_pedido = value;
					this.SendPropertyChanged("Id_pedido");
					this.OnId_pedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_cliente", DbType="Int")]
		public System.Nullable<int> Id_cliente
		{
			get
			{
				return this._Id_cliente;
			}
			set
			{
				if ((this._Id_cliente != value))
				{
					if (this._Tbl_Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_clienteChanging(value);
					this.SendPropertyChanging();
					this._Id_cliente = value;
					this.SendPropertyChanged("Id_cliente");
					this.OnId_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_empleado", DbType="Int")]
		public System.Nullable<int> Id_empleado
		{
			get
			{
				return this._Id_empleado;
			}
			set
			{
				if ((this._Id_empleado != value))
				{
					this.OnId_empleadoChanging(value);
					this.SendPropertyChanging();
					this._Id_empleado = value;
					this.SendPropertyChanged("Id_empleado");
					this.OnId_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fechapedido", DbType="Date")]
		public System.Nullable<System.DateTime> Fechapedido
		{
			get
			{
				return this._Fechapedido;
			}
			set
			{
				if ((this._Fechapedido != value))
				{
					this.OnFechapedidoChanging(value);
					this.SendPropertyChanging();
					this._Fechapedido = value;
					this.SendPropertyChanged("Fechapedido");
					this.OnFechapedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subtotal", DbType="Float")]
		public System.Nullable<double> subtotal
		{
			get
			{
				return this._subtotal;
			}
			set
			{
				if ((this._subtotal != value))
				{
					this.OnsubtotalChanging(value);
					this.SendPropertyChanging();
					this._subtotal = value;
					this.SendPropertyChanged("subtotal");
					this.OnsubtotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Float")]
		public System.Nullable<double> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Pedido_Tbl_DetallePedido", Storage="_Tbl_DetallePedido", ThisKey="Id_pedido", OtherKey="Id_pedido")]
		public EntitySet<Tbl_DetallePedido> Tbl_DetallePedido
		{
			get
			{
				return this._Tbl_DetallePedido;
			}
			set
			{
				this._Tbl_DetallePedido.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Pedido_Tbl_Empleado", Storage="_Tbl_Empleado", ThisKey="Id_pedido", OtherKey="Id_pedido")]
		public EntitySet<Tbl_Empleado> Tbl_Empleado
		{
			get
			{
				return this._Tbl_Empleado;
			}
			set
			{
				this._Tbl_Empleado.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Cliente_Tbl_Pedido", Storage="_Tbl_Cliente", ThisKey="Id_cliente", OtherKey="Id_cliente", IsForeignKey=true)]
		public Tbl_Cliente Tbl_Cliente
		{
			get
			{
				return this._Tbl_Cliente.Entity;
			}
			set
			{
				Tbl_Cliente previousValue = this._Tbl_Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Cliente.Entity = null;
						previousValue.Tbl_Pedido.Remove(this);
					}
					this._Tbl_Cliente.Entity = value;
					if ((value != null))
					{
						value.Tbl_Pedido.Add(this);
						this._Id_cliente = value.Id_cliente;
					}
					else
					{
						this._Id_cliente = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_Cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_DetallePedido(Tbl_DetallePedido entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Pedido = this;
		}
		
		private void detach_Tbl_DetallePedido(Tbl_DetallePedido entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Pedido = null;
		}
		
		private void attach_Tbl_Empleado(Tbl_Empleado entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Pedido = this;
		}
		
		private void detach_Tbl_Empleado(Tbl_Empleado entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Pedido = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Producto")]
	public partial class Tbl_Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_producto;
		
		private string _pro_Nombre;
		
		private string _pro_Descripcion;
		
		private System.Nullable<double> _pro_precio;
		
		private System.Nullable<int> _pro_stock;
		
		private System.Nullable<char> _pro_estado;
		
		private string _pro_imagen;
		
		private EntitySet<Tbl_Categoria> _Tbl_Categoria;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_productoChanging(int value);
    partial void OnId_productoChanged();
    partial void Onpro_NombreChanging(string value);
    partial void Onpro_NombreChanged();
    partial void Onpro_DescripcionChanging(string value);
    partial void Onpro_DescripcionChanged();
    partial void Onpro_precioChanging(System.Nullable<double> value);
    partial void Onpro_precioChanged();
    partial void Onpro_stockChanging(System.Nullable<int> value);
    partial void Onpro_stockChanged();
    partial void Onpro_estadoChanging(System.Nullable<char> value);
    partial void Onpro_estadoChanged();
    partial void Onpro_imagenChanging(string value);
    partial void Onpro_imagenChanged();
    #endregion
		
		public Tbl_Producto()
		{
			this._Tbl_Categoria = new EntitySet<Tbl_Categoria>(new Action<Tbl_Categoria>(this.attach_Tbl_Categoria), new Action<Tbl_Categoria>(this.detach_Tbl_Categoria));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_producto", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_producto
		{
			get
			{
				return this._Id_producto;
			}
			set
			{
				if ((this._Id_producto != value))
				{
					this.OnId_productoChanging(value);
					this.SendPropertyChanging();
					this._Id_producto = value;
					this.SendPropertyChanged("Id_producto");
					this.OnId_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_Nombre", DbType="VarChar(100)")]
		public string pro_Nombre
		{
			get
			{
				return this._pro_Nombre;
			}
			set
			{
				if ((this._pro_Nombre != value))
				{
					this.Onpro_NombreChanging(value);
					this.SendPropertyChanging();
					this._pro_Nombre = value;
					this.SendPropertyChanged("pro_Nombre");
					this.Onpro_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_Descripcion", DbType="VarChar(200)")]
		public string pro_Descripcion
		{
			get
			{
				return this._pro_Descripcion;
			}
			set
			{
				if ((this._pro_Descripcion != value))
				{
					this.Onpro_DescripcionChanging(value);
					this.SendPropertyChanging();
					this._pro_Descripcion = value;
					this.SendPropertyChanged("pro_Descripcion");
					this.Onpro_DescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_precio", DbType="Float")]
		public System.Nullable<double> pro_precio
		{
			get
			{
				return this._pro_precio;
			}
			set
			{
				if ((this._pro_precio != value))
				{
					this.Onpro_precioChanging(value);
					this.SendPropertyChanging();
					this._pro_precio = value;
					this.SendPropertyChanged("pro_precio");
					this.Onpro_precioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_stock", DbType="Int")]
		public System.Nullable<int> pro_stock
		{
			get
			{
				return this._pro_stock;
			}
			set
			{
				if ((this._pro_stock != value))
				{
					this.Onpro_stockChanging(value);
					this.SendPropertyChanging();
					this._pro_stock = value;
					this.SendPropertyChanged("pro_stock");
					this.Onpro_stockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_estado", DbType="Char(1)")]
		public System.Nullable<char> pro_estado
		{
			get
			{
				return this._pro_estado;
			}
			set
			{
				if ((this._pro_estado != value))
				{
					this.Onpro_estadoChanging(value);
					this.SendPropertyChanging();
					this._pro_estado = value;
					this.SendPropertyChanged("pro_estado");
					this.Onpro_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_imagen", DbType="VarChar(200)")]
		public string pro_imagen
		{
			get
			{
				return this._pro_imagen;
			}
			set
			{
				if ((this._pro_imagen != value))
				{
					this.Onpro_imagenChanging(value);
					this.SendPropertyChanging();
					this._pro_imagen = value;
					this.SendPropertyChanged("pro_imagen");
					this.Onpro_imagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Producto_Tbl_Categoria", Storage="_Tbl_Categoria", ThisKey="Id_producto", OtherKey="Id_producto")]
		public EntitySet<Tbl_Categoria> Tbl_Categoria
		{
			get
			{
				return this._Tbl_Categoria;
			}
			set
			{
				this._Tbl_Categoria.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Categoria(Tbl_Categoria entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Producto = this;
		}
		
		private void detach_Tbl_Categoria(Tbl_Categoria entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Usuario")]
	public partial class Tbl_Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_usuario;
		
		private string _usu_Nombre;
		
		private string _usu_password;
		
		private System.Nullable<int> _Id_empleado;
		
		private EntityRef<Tbl_Empleado> _Tbl_Empleado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_usuarioChanging(int value);
    partial void OnId_usuarioChanged();
    partial void Onusu_NombreChanging(string value);
    partial void Onusu_NombreChanged();
    partial void Onusu_passwordChanging(string value);
    partial void Onusu_passwordChanged();
    partial void OnId_empleadoChanging(System.Nullable<int> value);
    partial void OnId_empleadoChanged();
    #endregion
		
		public Tbl_Usuario()
		{
			this._Tbl_Empleado = default(EntityRef<Tbl_Empleado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_usuario
		{
			get
			{
				return this._Id_usuario;
			}
			set
			{
				if ((this._Id_usuario != value))
				{
					this.OnId_usuarioChanging(value);
					this.SendPropertyChanging();
					this._Id_usuario = value;
					this.SendPropertyChanged("Id_usuario");
					this.OnId_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_Nombre", DbType="VarChar(100)")]
		public string usu_Nombre
		{
			get
			{
				return this._usu_Nombre;
			}
			set
			{
				if ((this._usu_Nombre != value))
				{
					this.Onusu_NombreChanging(value);
					this.SendPropertyChanging();
					this._usu_Nombre = value;
					this.SendPropertyChanged("usu_Nombre");
					this.Onusu_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_password", DbType="VarChar(100)")]
		public string usu_password
		{
			get
			{
				return this._usu_password;
			}
			set
			{
				if ((this._usu_password != value))
				{
					this.Onusu_passwordChanging(value);
					this.SendPropertyChanging();
					this._usu_password = value;
					this.SendPropertyChanged("usu_password");
					this.Onusu_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_empleado", DbType="Int")]
		public System.Nullable<int> Id_empleado
		{
			get
			{
				return this._Id_empleado;
			}
			set
			{
				if ((this._Id_empleado != value))
				{
					if (this._Tbl_Empleado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_empleadoChanging(value);
					this.SendPropertyChanging();
					this._Id_empleado = value;
					this.SendPropertyChanged("Id_empleado");
					this.OnId_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Empleado_Tbl_Usuario", Storage="_Tbl_Empleado", ThisKey="Id_empleado", OtherKey="Id_empleado", IsForeignKey=true)]
		public Tbl_Empleado Tbl_Empleado
		{
			get
			{
				return this._Tbl_Empleado.Entity;
			}
			set
			{
				Tbl_Empleado previousValue = this._Tbl_Empleado.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Empleado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Empleado.Entity = null;
						previousValue.Tbl_Usuario.Remove(this);
					}
					this._Tbl_Empleado.Entity = value;
					if ((value != null))
					{
						value.Tbl_Usuario.Add(this);
						this._Id_empleado = value.Id_empleado;
					}
					else
					{
						this._Id_empleado = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_Empleado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
